### ISSUE TITLE
bug: message.author.color always returns empty

### ISSUE THREAD

**Issue by parknich** [PythonistaGuild/TwitchIO#445]
Steps to reproduce: print message.author.color, observe results

**Comment by IAmTomahawkx** [comment]
Hi sorry for the delay. This value is grabbed directly from the payload provided by Twitch. Typically, the colour is *not* predetermined, and as such is empty. This will be the case for most chatters (visible when you chat in a channel that has a chat overlay, the colours you see for most will be different than the colours on the overlay). 
Where this comes in is for users that have turbo or twitch prime, who are able to select a colour to be used for them by everyone.
