### ISSUE TITLE
command.Context get_user returns an object type of Chatter but says it returns User

### ISSUE THREAD

**Issue by sernone** [PythonistaGuild/TwitchIO#447]
When executing a command and retrieving the command.Context object i noticed that the get_user function on the Context says it returns a User or PartialUser however it is returning a Chatter class.

![image](https://github.com/PythonistaGuild/TwitchIO/assets/9544741/736ffc21-5bcd-4679-983a-a071d3d872f0)
<class 'twitchio.chatter.Chatter'>
'Chatter' object has no attribute 'fetch_followers'

**Comment by chillymosh** [comment]
This is supposed to return a Chatter / PartialChatter and not PartialUser / User as it uses the IRC Chatter cache.

To fetch the actual User object from a Chatter you can do `await Chatter.user()` 

I'll update the return types.

**Comment by chillymosh** [comment]
@sernone if you install from git / master branch, instead of pypi, this should be corrected now.

**Comment by sernone** [comment]
@chillymosh awesome thank you sir , that is what i ended up doing anyway i figured it was just a mistake in the return type
