### ISSUE TITLE
AttributeError in console, but correct message in chat

### ISSUE THREAD

**Issue by bxrbeq** [PythonistaGuild/TwitchIO#471]
Hi, i'm on version 2.10.0 and im getting the following error into the console:

        File "C:\Users\---\AppData\Local\Programs\Python\Python312\Lib\site-packages\twitchio\client.py", line 208, in wrapped
            await func(*args)
        File "c:\Users\---\Documents\coding\python\twitch-bot\bxrbeq-bot.py", line 207, in event_message
            user = message.author.name
                   ^^^^^^^^^^^^^^^^^^^
        AttributeError: 'NoneType' object has no attribute 'name'

in 

        async def event_message(self, message):
                global NICK, CLIENT_ID,TOKENTWITCH
                user = message.author.name
                message_content = message.content
                msg = message.channel
                if user != NICK:
                    if ('hallo' in message_content.lower() or 'hi' in message_content.lower()):
                        await msg.send(f'Hallo {user}')

but the message in the chat still has the authors name in it:
![Image](https://github.com/user-attachments/assets/20ba5a3b-d9f8-4052-b6d2-81672d7981a2)

Am I doing something wrong?

**Comment by chillymosh** [comment]
First, do not use `global` variables, they are extremely bad practice, especially in an OOP framework such as TwitchIO.

I refer you to the quickstart docs, the second example:  https://twitchio.dev/en/latest/quickstart.html

```
from twitchio.ext import commands

class Bot(commands.Bot):

    def __init__(self):
        # Initialise our Bot with our access token, prefix and a list of channels to join on boot...
        # prefix can be a callable, which returns a list of strings or a string...
        # initial_channels can also be a callable which returns a list of strings...
        super().__init__(token='ACCESS_TOKEN', prefix='?', initial_channels=['...'])

    async def event_ready(self):
        # Notify us when everything is ready!
        # We are logged in and ready to chat and use commands...
        print(f'Logged in as | {self.nick}')
        print(f'User id is | {self.user_id}')

    async def event_message(self, message):
        # Messages with echo set to True are messages sent by the bot...
        # For now we just want to ignore them...
        if message.echo:
            return

        # Print the contents of our message to console...
        print(message.content)

        # Since we have commands and are overriding the default `event_message`
        # We must let the bot know we want to handle and invoke our commands...
        await self.handle_commands(message)
```

I would also opt to doing this, in you case.

```
if any(word in message_content.lower() for word in ['hallo', 'hi']):
```
