### ISSUE TITLE
User.create_marker() returns HTTP 404 Not Found

### ISSUE THREAD

**Issue by eelcohn** [PythonistaGuild/TwitchIO#474]
When I try to create a strean marker with TwitchIO v2.10.0 I get a HTTP 404 Not Found error:
```
    await self._api._user.create_marker(
  File "/opt/project/venv/lib/python3.12/site-packages/twitchio/user.py", line 750, in create_marker
    data = await self._http.post_stream_marker(token, user_id=str(self.id), description=description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/project/venv/lib/python3.12/site-packages/twitchio/http.py", line 741, in post_stream_marker
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/project/venv/lib/python3.12/site-packages/twitchio/http.py", line 154, in request
    body, is_text = await self._request(route, path, headers, force_app_token=force_app_token)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/project/venv/lib/python3.12/site-packages/twitchio/http.py", line 253, in _request
    raise errors.HTTPException(f"Failed to fulfill the request", reason=resp.reason, status=resp.status)
twitchio.errors.HTTPException: 404: Failed to fulfill the request: Not Found
```
Possibly this is due to the call from `post_stream_marker()` is to a wrong Twitch API endpoint, see [](https://dev.twitch.tv/docs/api/reference/#create-stream-marker). It looks like it should be a function of the Stream() object, not the User() or PartialUser() object?

**Comment by chillymosh** [comment]
The endpoint is correct and this is supposed to be a PartialUser method.

The reasons for 404 are:

- The user is not streaming live.
- The ID in the user_id field is not valid (if user is manually created)
- The user hasn't enabled video on demand (VOD).

**Comment by eelcohn** [comment]
Hi @chillymosh, thank you for your swift reply. In my case it's probably caused by the first reason: the user is not streaming live. I was trying to set the channel's tags _before_ the user begins a livestream.
