### ISSUE TITLE
Client-ID header missing when providing own ClientSession

### ISSUE THREAD

**Issue by LostLuma** [PythonistaGuild/TwitchIO#476]
When providing your own `ClientSession` for the client `HTTPClient._init_session` exits early and the `Client-ID` header will not be set on requests to Twitch, as it's set on the session instead of a per-request basis.
https://github.com/PythonistaGuild/TwitchIO/blob/44c93a97c77ab63414148b336adac6e86c7c429d/twitchio/http.py#L395-L404

**Comment by chillymosh** [comment]
Just to add to this from other discussions, when an existing ClientSession is passed it is closed when Client.close() is called.
We should ignore closing provided sessions as it can impact other services depending upon it.

Something akin to

```
   def __init__(self) -> None:
        if session is None:
            self._session = aiohttp.ClientSession()
            self._should_close_session = True
        else:
            self._session: aiohttp.ClientSession = session
            self._should_close_session = False

    async def close(self) -> None:
        """Close the persistent connection to the database."""
        if self._should_close_session:
            await self._session.close()
```
